# Generated by Django 4.1.2 on 2022-11-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_alter_moment_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moment',
            options={'ordering': ['project', 'seq_nr']},
        ),
    ]
