# Generated by Django 4.1.2 on 2022-11-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='respondent',
            table='respondents',
        ),
    ]
