# Generated by Django 4.1.2 on 2022-11-03 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0002_alter_respondent_table'),
        ('schedules', '0003_alter_schedule_options'),
        ('measurements', '0003_alter_measurement_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respondents.respondent'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule'),
        ),
    ]
