# Generated by Django 4.1.2 on 2022-11-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['project', 'name']},
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('CRF', 'CRF'), ('QST', 'QST')], default='QST', max_length=25),
            preserve_default=False,
        ),
    ]
