# Generated by Django 4.1.2 on 2022-11-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_survey_options_survey_survey_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['project', 'survey_type', 'name']},
        ),
    ]
