# Generated by Django 4.1.2 on 2022-11-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schedule',
            table='schedules',
        ),
    ]
