# Generated by Django 4.1.2 on 2022-11-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_schedule_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['project', 'moment', 'survey']},
        ),
    ]
