# Generated by Django 4.1.2 on 2022-11-03 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0003_alter_moment_options'),
        ('surveys', '0003_alter_survey_options'),
        ('projects', '0003_remove_project_created'),
        ('schedules', '0003_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='moment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='moments.moment'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey'),
        ),
    ]
